// Turns an animation frame into a flat grid of colors ("the scene").
//
// This module is pure (no DOM), so the very same code renders the live pet on
// a canvas and the PNG previews generated by scripts/render-sprites.mjs.

import {
  ANIMATIONS,
  OUTLINE,
  SHADOW,
  SPRITE_H,
  SPRITE_W,
  STAMPS,
  type Grid,
  type Palette,
  type PetState,
} from "./sprites.ts";

/** Scene size in big pixels. The window is SCENE_W*8 x SCENE_H*8 CSS pixels. */
export const SCENE_W = 16;
export const SCENE_H = 18;
export const PIXEL_SCALE = 8;

/** Top-left corner of the 10x9 sprite inside the scene, before frame offsets. */
const SPRITE_X = 3;
const SPRITE_Y = 6;
/** Row the creature stands on; the soft shadow is drawn here. */
const GROUND_Y = SPRITE_Y + SPRITE_H;
const XP_BAR_Y = SCENE_H - 1;
const XP_BAR_CELLS = 10;

/** Row-major list of CSS colors, `null` = transparent. */
export type Scene = (string | null)[];

export interface Hud {
  level: number;
  /** Progress towards the next level, 0..1. */
  progress: number;
}

export function composeScene(state: PetState, frameIndex: number, hud?: Hud): Scene {
  const anim = ANIMATIONS[state];
  const frame = anim.frames[frameIndex % anim.frames.length];
  const dx = frame.dx ?? 0;
  const dy = frame.dy ?? 0;

  // 1. Opaque art: creature, decorations and (optionally) the level label.
  const art: Scene = new Array(SCENE_W * SCENE_H).fill(null);
  stamp(art, frame.sprite, SPRITE_X + dx, SPRITE_Y + dy, anim.palette);
  for (const fx of frame.fx ?? []) {
    // Decorations stay put while the body jumps or shakes.
    stamp(art, STAMPS[fx.stamp], SPRITE_X + fx.x, SPRITE_Y + fx.y, anim.palette);
  }
  if (hud) drawText(art, `LV${hud.level}`, 1, 0);

  // 2. Outline: every transparent pixel touching art (4-neighbourhood) becomes
  //    dark. Done as a separate pass so the art itself never has to include
  //    an outline and stays easy to edit.
  const scene: Scene = art.slice();
  for (let y = 0; y < SCENE_H; y++) {
    for (let x = 0; x < SCENE_W; x++) {
      if (art[idx(x, y)] !== null) continue;
      if (opaque(art, x - 1, y) || opaque(art, x + 1, y) || opaque(art, x, y - 1) || opaque(art, x, y + 1)) {
        scene[idx(x, y)] = OUTLINE;
      }
    }
  }

  // 3. Soft shadow on the ground; it shrinks while the pet is in the air.
  const inset = dy < 0 ? 2 : 1;
  for (let x = SPRITE_X + inset; x < SPRITE_X + SPRITE_W - inset; x++) {
    if (scene[idx(x, GROUND_Y)] === null) scene[idx(x, GROUND_Y)] = SHADOW;
  }

  // 4. XP bar under the pet (only while hovering, see main.ts).
  if (hud) {
    const filled = Math.round(Math.min(Math.max(hud.progress, 0), 1) * XP_BAR_CELLS);
    for (let i = 0; i < XP_BAR_CELLS; i++) {
      scene[idx(SPRITE_X + i, XP_BAR_Y)] = i < filled ? anim.palette.y : OUTLINE;
    }
  }

  return scene;
}

// ---------------------------------------------------------------------------

const idx = (x: number, y: number) => y * SCENE_W + x;

function opaque(scene: Scene, x: number, y: number): boolean {
  return x >= 0 && y >= 0 && x < SCENE_W && y < SCENE_H && scene[idx(x, y)] !== null;
}

function stamp(scene: Scene, grid: Grid, ox: number, oy: number, palette: Palette): void {
  grid.forEach((row, y) => {
    [...row].forEach((ch, x) => {
      if (ch === ".") return;
      const sx = ox + x;
      const sy = oy + y;
      if (sx < 0 || sy < 0 || sx >= SCENE_W || sy >= SCENE_H) return;
      scene[idx(sx, sy)] = palette[ch] ?? "#ff00ff"; // magenta = unknown char
    });
  });
}

// 3x5 pixel font, just enough for "LV12".
const FONT: Readonly<Record<string, Grid>> = {
  L: ["w..", "w..", "w..", "w..", "www"],
  V: ["w.w", "w.w", "w.w", "w.w", ".w."],
  "0": ["www", "w.w", "w.w", "w.w", "www"],
  "1": [".w.", "ww.", ".w.", ".w.", "www"],
  "2": ["www", "..w", "www", "w..", "www"],
  "3": ["www", "..w", ".ww", "..w", "www"],
  "4": ["w.w", "w.w", "www", "..w", "..w"],
  "5": ["www", "w..", "www", "..w", "www"],
  "6": ["www", "w..", "www", "w.w", "www"],
  "7": ["www", "..w", "..w", ".w.", ".w."],
  "8": ["www", "w.w", "www", "w.w", "www"],
  "9": ["www", "w.w", "www", "..w", "www"],
};

const TEXT_PALETTE: Palette = { w: "#fff1e8" };

function drawText(scene: Scene, text: string, x: number, y: number): void {
  for (const ch of text) {
    const glyph = FONT[ch];
    if (glyph) stamp(scene, glyph, x, y, TEXT_PALETTE);
    x += 4;
  }
}
