// Turns an animation frame into a flat grid of colors ("the scene").
//
// This module is pure (no DOM), so the very same code renders the live pet on
// a canvas and the PNG previews generated by scripts/render-sprites.mjs.

import { skinPalette, SKINS, type SkinId } from "./skins.ts";
import {
  ACCESSORIES,
  ANIMATIONS,
  OUTLINE,
  SHADOW,
  SPRITE_H,
  SPRITE_W,
  STAMPS,
  type Grid,
  type Palette,
  type PetState,
} from "./sprites.ts";

/** Scene size in big pixels. The canvas is SCENE_W*8 x SCENE_H*8 CSS pixels. */
export const SCENE_W = 16;
export const SCENE_H = 18;
export const PIXEL_SCALE = 8;

/** Top-left corner of the 10x9 sprite inside the scene, before frame offsets. */
const SPRITE_X = 3;
const SPRITE_Y = 6;
/** Row the creature stands on; the soft shadow is drawn here. */
const GROUND_Y = SPRITE_Y + SPRITE_H;
const XP_BAR_Y = SCENE_H - 1;
const XP_BAR_CELLS = 10;
/** Length of the level-up confetti shower. */
export const PARTY_MS = 4000;

/** Row-major list of CSS colors, `null` = transparent. */
export type Scene = (string | null)[];

export interface Hud {
  level: number;
  /** Progress towards the next level, 0..1. */
  progress: number;
  /** Draw "LV<n>" above the pet (default true). */
  label?: boolean;
}

export interface SceneOptions {
  /** Show the level label and XP bar. */
  hud?: Hud;
  skin?: SkinId;
  /** Unlocks accessories (see ACCESSORIES in sprites.ts). */
  level?: number;
  /** Milliseconds since a level-up; draws confetti while < PARTY_MS. */
  party?: number;
}

export function composeScene(state: PetState, frameIndex: number, opts: SceneOptions = {}): Scene {
  const anim = ANIMATIONS[state];
  const frame = anim.frames[frameIndex % anim.frames.length];
  const skin = opts.skin ?? "classic";
  const palette = skinPalette(anim.palette, skin, state);
  const outline = SKINS[skin]?.outline ?? OUTLINE;
  const dx = frame.dx ?? 0;
  const dy = frame.dy ?? 0;

  // 1. Opaque art: creature, accessories, decorations, level label.
  const art: Scene = new Array(SCENE_W * SCENE_H).fill(null);
  stamp(art, frame.sprite, SPRITE_X + dx, SPRITE_Y + dy, palette);
  const top = headTop(frame.sprite);
  for (const acc of ACCESSORIES) {
    if ((opts.level ?? 1) < acc.minLevel) continue;
    // Sits on the head, so it follows jumps and the squashed breathing frame.
    stamp(art, acc.grid, SPRITE_X + dx + acc.x, SPRITE_Y + dy + top - acc.grid.length, palette);
  }
  for (const fx of frame.fx ?? []) {
    // Decorations stay put while the body jumps or shakes.
    stamp(art, STAMPS[fx.stamp], SPRITE_X + fx.x, SPRITE_Y + fx.y, palette);
  }
  if (opts.hud && opts.hud.label !== false) drawText(art, `LV${opts.hud.level}`, 1, 0);

  // 2. Outline: every transparent pixel touching art (4-neighbourhood) becomes
  //    dark. Done as a separate pass so the art itself never has to include
  //    an outline and stays easy to edit.
  const scene: Scene = art.slice();
  for (let y = 0; y < SCENE_H; y++) {
    for (let x = 0; x < SCENE_W; x++) {
      if (art[idx(x, y)] !== null) continue;
      if (opaque(art, x - 1, y) || opaque(art, x + 1, y) || opaque(art, x, y - 1) || opaque(art, x, y + 1)) {
        scene[idx(x, y)] = outline;
      }
    }
  }

  // 3. Soft shadow on the ground; it shrinks while the pet is in the air.
  const inset = dy < 0 ? 2 : 1;
  for (let x = SPRITE_X + inset; x < SPRITE_X + SPRITE_W - inset; x++) {
    if (scene[idx(x, GROUND_Y)] === null) scene[idx(x, GROUND_Y)] = SHADOW;
  }

  // 4. XP bar under the pet (only while hovering, see main.ts).
  if (opts.hud) {
    const filled = Math.round(Math.min(Math.max(opts.hud.progress, 0), 1) * XP_BAR_CELLS);
    for (let i = 0; i < XP_BAR_CELLS; i++) {
      scene[idx(SPRITE_X + i, XP_BAR_Y)] = i < filled ? palette.y : outline;
    }
  }

  // 5. Level-up confetti, falling through the empty space around the pet.
  if (opts.party !== undefined && opts.party >= 0 && opts.party < PARTY_MS) {
    drawConfetti(scene, opts.party, palette);
  }

  return scene;
}

/** First sprite row (from the top) that belongs to the body, ignoring the antenna. */
function headTop(grid: Grid): number {
  for (let y = 0; y < grid.length; y++) {
    // The antenna is a single column; the body is at least 4 pixels wide.
    if ([...grid[y]].filter((ch) => ch !== ".").length >= 4) return y;
  }
  return 2;
}

const CONFETTI = 18;

function drawConfetti(scene: Scene, ms: number, palette: Palette): void {
  const colors = [palette.y, palette.r, palette.b, palette.P, palette.w, palette.g];
  for (let i = 0; i < CONFETTI; i++) {
    // Cheap deterministic "random" numbers per particle.
    const r1 = hash(i * 7 + 1);
    const r2 = hash(i * 13 + 5);
    const speed = 0.006 + r2 * 0.008; // big pixels per ms
    const y = Math.floor(-r1 * 10 + ms * speed);
    const x = Math.floor(r2 * SCENE_W + Math.sin(ms / 220 + i) * 1.2);
    if (y < 0 || y >= SCENE_H - 1 || x < 0 || x >= SCENE_W) continue;
    if (scene[idx(x, y)] === null) scene[idx(x, y)] = colors[i % colors.length];
  }
}

function hash(n: number): number {
  const x = Math.sin(n * 12.9898) * 43758.5453;
  return x - Math.floor(x);
}

// ---------------------------------------------------------------------------

const idx = (x: number, y: number) => y * SCENE_W + x;

function opaque(scene: Scene, x: number, y: number): boolean {
  return x >= 0 && y >= 0 && x < SCENE_W && y < SCENE_H && scene[idx(x, y)] !== null;
}

function stamp(scene: Scene, grid: Grid, ox: number, oy: number, palette: Palette): void {
  grid.forEach((row, y) => {
    [...row].forEach((ch, x) => {
      if (ch === ".") return;
      const sx = ox + x;
      const sy = oy + y;
      if (sx < 0 || sy < 0 || sx >= SCENE_W || sy >= SCENE_H) return;
      scene[idx(sx, sy)] = palette[ch] ?? "#ff00ff"; // magenta = unknown char
    });
  });
}

// 3x5 pixel font, just enough for "LV12".
const FONT: Readonly<Record<string, Grid>> = {
  L: ["w..", "w..", "w..", "w..", "www"],
  V: ["w.w", "w.w", "w.w", "w.w", ".w."],
  "0": ["www", "w.w", "w.w", "w.w", "www"],
  "1": [".w.", "ww.", ".w.", ".w.", "www"],
  "2": ["www", "..w", "www", "w..", "www"],
  "3": ["www", "..w", ".ww", "..w", "www"],
  "4": ["w.w", "w.w", "www", "..w", "..w"],
  "5": ["www", "w..", "www", "..w", "www"],
  "6": ["www", "w..", "www", "w.w", "www"],
  "7": ["www", "..w", "..w", ".w.", ".w."],
  "8": ["www", "w.w", "www", "w.w", "www"],
  "9": ["www", "w.w", "www", "..w", "www"],
};

const TEXT_PALETTE: Palette = { w: "#fff1e8" };

function drawText(scene: Scene, text: string, x: number, y: number): void {
  for (const ch of text) {
    const glyph = FONT[ch];
    if (glyph) stamp(scene, glyph, x, y, TEXT_PALETTE);
    x += 4;
  }
}
